= Wyn K Heng - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Bluebird

Bluebird is a desktop based organisational tool for the working parent on the go. Bluebird is suitable
for a variety of day-to-day management tasks, including managing appointments for both yourself and your
child, and also organising the contact information from your Address Book. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 15 kLoC. +


This project portfolio serves to provide an insight into how Wyn K Heng has contributed to project Bluebird. Included
in this portfolio are the enhancements, features, tests and proposed enhancements that Wyn K Heng has contribued to the project.

*Code contributed*: [[https://github.com/CS2103AUG2017-T15-B4/main/blob/master/collated/main/wynkheng.md[Functional code]] [https://github.com/CS2103AUG2017-T15-B4/main/blob/master/collated/test/wynkheng.md[Test code]]

=== Enhancement Added: Hide/Unhide

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=hide]
include::../UserGuide.adoc[tag=unhide]

#End of Extract#

---

==== Justification

Since this application is directed largely at working parents who occasionally allow their children to explore the
the application, there might be contacts in Bluebird's address book that the parent might not want the child to see.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=hide]
include::../DeveloperGuide.adoc[tag=unhide]

#End of Extract#

---

=== Enhancement Proposed: Hide/Unhide tasks

Similar to having hide/unhide for person contacts, having hide/unhide for tasks would allow parent users to conceal
tasks that they wouldn't want their child to see. For example, doctor appointments or other sensitive tasks.

=== Enhancement Proposal:

=== Other contributions

* Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}
